/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorVistas;

/**
 *
 * @author krypt97
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ControladorVistas miControladorVistas;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JButton();
        btnColaEspera = new javax.swing.JButton();
        btnColaLlenado = new javax.swing.JButton();
        btnRechazados = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Queuing system project");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        jLabel1.setText("Sistema de colas  - LLenado balones de oxígeno");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 18, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        btnRegistrar.setText("Registrar pedido");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar(evt);
            }
        });
        jPanel2.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 9, 140, 42));

        btnColaEspera.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        btnColaEspera.setText("Cola de espera");
        btnColaEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColaEspera(evt);
            }
        });
        jPanel2.add(btnColaEspera, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 9, 140, 42));

        btnColaLlenado.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        btnColaLlenado.setText("Cola de llenado");
        btnColaLlenado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColaLlenado(evt);
            }
        });
        jPanel2.add(btnColaLlenado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 9, 140, 42));

        btnRechazados.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        btnRechazados.setText("Rechazados");
        btnRechazados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechazados(evt);
            }
        });
        jPanel2.add(btnRechazados, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 9, 140, 42));

        btnHistorial.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        btnHistorial.setText("Historial");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorial(evt);
            }
        });
        jPanel2.add(btnHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 9, 140, 42));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar
        // TODO add your handling code here:
        miControladorVistas.mostrarPanelRegistrarPedido();
    }//GEN-LAST:event_btnRegistrar

    private void btnColaEspera(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColaEspera
        // TODO add your handling code here:
        miControladorVistas.mostrarPanelColaEspera();
    }//GEN-LAST:event_btnColaEspera

    private void btnColaLlenado(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColaLlenado
        // TODO add your handling code here:
        miControladorVistas.mostrarPanelColaLlenado();
    }//GEN-LAST:event_btnColaLlenado

    private void btnRechazados(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechazados
        // TODO add your handling code here:
        miControladorVistas.mostrarPanelPedidosRechazados();
    }//GEN-LAST:event_btnRechazados

    private void btnHistorial(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorial
        // TODO add your handling code here:
        miControladorVistas.mostrarPanelHistorialPedidos();
    }//GEN-LAST:event_btnHistorial

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        miControladorVistas.guardarDatosEnArchivo();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColaEspera;
    private javax.swing.JButton btnColaLlenado;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnRechazados;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

    // Enlace a controlador vistas
    public void setControladorVistas(ControladorVistas miControladorVistas) {
        this.miControladorVistas = miControladorVistas;
    }
}
